baseURL: "https://maiphuongpham.github.io/blog/"
languageCode: en-us
title: Mai Pham
theme: PaperMod

menu:
  main:
    - identifier: introduction
      name: Introduction
      url: introduction
      weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30

params:
    defaultTheme: auto
    disableThemeToggle: false
    ShowBreadCrumbs: false
    ShowPostNavLinks: true
    ShowShareButtons: true
    ShareButtons: ['facebook','twitter','linkedin']
    TocOpen: true
    homeInfoParams:
        Title: Knowing is Growing
        Content: "Learning is an incessant voyage of discovery, \
        which demands prodigious time and a rigorous endeavor. \
        This blog serves as a repository to perpetuate and nurture \
        my intellectual prowess while graciously sharing the delight \
        of acquiring knowledge with fellow seekers of wisdom. \
        May your time here be filled with inspiration, \
        enlightenment, and a profound sense of fulfillment."
    
    socialIcons: 
        - name: linkedin
          url: https://www.linkedin.com/in/maippham99
        - name: github
          url: https://maiphuongpham.github.io
        - name: googlescholar
          url: https://scholar.google.com/citations?user=dRXdxPIAAAAJ&hl=en
        - name: discord
          url: https://discord.gg/Kg4q9Tv9na
        - name: instagram
          url: https://www.instagram.com/maihoamieu