baseURL: "https://maipham.netlify.app"
languageCode: en-us
title: Mai Pham
theme: PaperMod

menu:
  main:
    - identifier: introduction
      name: introduction
      url: "/maipham/content/introduction.md/"
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
